import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Generated by `wrangler types` / cf-typegen — see package.json.
    "cloudflare-env.d.ts",
    // Not covered by eslint-config-next's defaults, and using
    // globalIgnores() here replaces rather than extends them:
    "node_modules/**",
    ".open-next/**",
    "drizzle/**",
    // Throwaway Phase 0.5 spike — separate package, own conventions, gets
    // deleted per BUILD_SEQUENCE.md once results are recorded.
    "spike/**",
  ]),
]);

export default eslintConfig;
